SocialMedia/SocialMedia/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("",include ("mainapp.urls")),
    path("",include ("django.contrib.auth.urls"))
]

SocialMedia/mainapp/urls.py
from django.urls import path, include
from . import views



app_name="mainapp"

urlpatterns = [
    path("", views.base, name="base"),
    path('signup',views.SignUpView.as_view(), name="signup"),
    path("profileCreate",views.profileCreate, name="profileCreate")
]

SocialMedia/mainapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator


class Profile(models.Model):
    username = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    profile_image = models.ImageField(blank=True, upload_to='images/', null=True)
    cover_image=models.ImageField(blank=True, upload_to='images/', null=True)
    email=models.EmailField(max_length=250, null=True)
    age=models.IntegerField(validators=[MaxValueValidator(120),MinValueValidator(12)], null=True)
    info=models.TextField(blank=True, null=True)


    def __str__(self):
        return f"Profile: {self.username} E-mail: {self.email} Age: {self.age} Info: {self.info}" 

SocialMedia/mainapp/views.py
from django.shortcuts import render, redirect
from . import models
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required, user_passes_test
from django.utils.decorators import method_decorator
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import CreateView


def not_logged_in(user):
    return not user.is_authenticated

class SignUpView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = "registration/signup.html"

    @method_decorator(user_passes_test(not_logged_in, redirect_field_name=None, login_url="/"))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


def base(request):
    return render(request,'base.html')

@login_required(login_url="/login")
def profileCreate(request):
    check = models.Profile.objects.filter(username=request.user)
    if check:
        return redirect(reverse('mainapp:base'))
    else:
        if request.POST:  
            profile_image=request.POST["profile_image"]
            cover_image = request.POST["cover_image"]
            email=request.POST["email"]
            age=request.POST["age"]
            info=request.POST["info"]
            models.Profile.objects.create(username=request.user, profile_image=profile_image, cover_image=cover_image, email=email, age=age, info=info)
            return redirect(reverse('mainapp:base'))
        else:
            return render(request, 'registration/profilecreation.html')

SocialMedia/templates/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <title>Swap Media</title>
</head>
<body>

    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'mainapp:base' %}">Swap Media</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Stream</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Add Post</a>
              </li>
              {% if user.is_authenticated %}
              <li class="nav-item" style="position: absolute; right: 0px; padding: 0px 10px;">
                <form method="post" action="{% url 'logout' %}?next=/" style="height: 5px;">
                  {% csrf_token %}
                  <button type="submit" class="nav-link">Logout</button>
                </form>
              </li>
              {% else %}
              <div class="nav-item" style="position: absolute; right: 0px; padding: 0px 10px;">
              <li class="nav-item" style="float: left;">
                <a class="nav-link" href="{% url 'login' %}">Login</a>
              </li>
              <li class="nav-item" style="float: left;">
                <a class="nav-link" href="{% url 'mainapp:signup' %}?next=/profileCreate">SignUp</a>
              </li>
              </div>
              {%endif%}
            </ul>
          </div>
        </div>
      </nav>
    
    {% block content %}

    {% endblock %}

</body>
</html>